####################################################################
# VSTS Build Configuration, Version 1.3
#
# (c)2020 superdev GmbH
####################################################################

name: 1.1.$(date:yy)$(DayOfYear).$(rev:rr)

pool:
  vmImage: 'windows-2019'

trigger:
  branches:
    include:
    - master
    - develop
    - release/*
    - feature/*

  paths:
    exclude:
    - README.md

variables:
  solution: 'HttpClient.Caching.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildVersionPostfix: '-pre'

steps:
- task: bleddynrichards.Assembly-Info-Task.Assembly-Info-NetCore.Assembly-Info-NetCore@2
  displayName: 'Set Assembly Manifest Data'
  inputs:
    FileNames: |
     HttpClient.Caching.csproj
    InsertAttributes: true
    Product: 'HttpClient.Caching'
    Description: ''
    Company: 'superdev GmbH'
    Copyright: '(c) $(date:YYYY) superdev GmbH'
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.x'
  inputs:
    versionSpec: 5.x

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(solution)'

- powershell: |
   Write-Host "##vso[task.setvariable variable=PackageVersion]$(Build.BuildNumber)"
   Write-Host "##vso[task.setvariable variable=PackageVersionPre]$(Build.BuildNumber)$(BuildVersionPostfix)"
  displayName: 'Set PackageVersion'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    msbuildArgs: ''
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run UnitTests'
  inputs:
    command: test
    projects: '**/*.Tests.csproj'
    arguments: '--framework netcoreapp3.1'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet PreRelease'
  inputs:
    command: pack
    packagesToPack: HttpClient.Caching/HttpClient.Caching.csproj
    versioningScheme: byEnvVar
    versionEnvVar: PackageVersionPre

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Prod'
  inputs:
    command: pack
    packagesToPack: HttpClient.Caching/HttpClient.Caching.csproj
    versioningScheme: byEnvVar
    versionEnvVar: PackageVersion

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'

    Contents: |
     **\bin\$(BuildConfiguration)\**
     **\bin\*.nupkg

    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
